=== hilotec/elexis-base/elexis/src/ch/elexis/exchange/xchange.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated from EMRSample.xml by XMLBuddy -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="SgamXChange"
           xmlns="SgamXChange"
           elementFormDefault="qualified">
	<xs:element name="XCHANGE" type="xChangeDescriptor"/>	
	<xs:element name="address" type="addressType">

		<xs:annotation>
			<xs:documentation>
				The contents of the Element is a label /
				address-sticker. Linebreaks can be
				&lt;lf&gt; or &lt;crlf&gt; 
			</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="allergies">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="allergy" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="allergy">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="confirmed" type="xs:NMTOKEN" use="required"/>
					<xs:attribute name="first" type="xs:NMTOKEN" use="required"/>
					<xs:attribute name="substance" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="analyse">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="image" maxOccurs="1"/>
				<xs:element ref="result" maxOccurs="1"/>
			</xs:choice>
			<xs:attribute name="abnormal" type="xs:boolean"/>
			<xs:attribute name="classification" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="date" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="id" type="xs:NMTOKEN"/>
			<xs:attribute name="lab" type="xs:integer" use="required"/>
			<xs:attribute name="normRange" type="xs:NMTOKEN"/>
			<xs:attribute name="param" type="xs:string" use="required"/>
			<xs:attribute name="type" type="xs:NMTOKEN"/>
			<xs:attribute name="unit" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="analyses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="analyse" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="anamnesis">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="episode" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="connection">
		<xs:complexType>
			<xs:attribute name="identification" type="xs:string" use="required"/>
			<xs:attribute name="type" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="contact" type="xChangeContact">
	</xs:element>
	<xs:element name="association">
		<xs:complexType>
			<xs:attribute name="id" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="type" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="diagnosis">
		<xs:complexType>
			<xs:attribute name="code" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="codesystem" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="document" type="xChangeDocument">
	</xs:element>
	<xs:element name="documents">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="document" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="episode" type="xChangeEpisode">
	</xs:element>
	<xs:element name="image">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="content" type="xs:NMTOKEN" use="required"/>
					<xs:attribute name="hint" type="xs:NMTOKEN" use="required"/>
					<xs:attribute name="id" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="medical">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="anamnesis"/>
				<xs:element ref="records"/>
				<xs:element ref="analyses"/>
				<xs:element ref="documents"/>
				<xs:element ref="medications"/>
				<xs:element ref="allergies"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="medication">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="dosage" type="xs:NMTOKEN" use="required"/>
					<xs:attribute name="id" type="xs:integer" use="required"/>
					<xs:attribute name="last" type="xs:NMTOKEN" use="required"/>
					<xs:attribute name="start" type="xs:NMTOKEN" use="required"/>
					<xs:attribute name="substance" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="medications">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="medication" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="record">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="text"/>
				<xs:element ref="episode" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="author" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="date" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="id" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="responsible" type="xs:NMTOKEN"/>
			<xs:attribute name="responsibleEAN" type="xs:integer"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="records">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="record" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="result" type="xs:string"/>
	<xs:element name="section">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="summary" type="xs:string"/>
	<xs:element name="text">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="section"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="zip" type="xs:string"/>

	<xs:complexType name="addressType" mixed="true">

		<xs:attribute name="street" type="xs:string"></xs:attribute>
		<xs:attribute name="zip" type="xs:string"></xs:attribute>
		<xs:attribute name="city" type="xs:string"></xs:attribute>
		<xs:attribute name="country" type="xs:string"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="xChangeDescriptor">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded"
				ref="document">
			</xs:element>
			<xs:element minOccurs="1" maxOccurs="unbounded"
				ref="contact">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="xChangeContact">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element minOccurs="0" maxOccurs="unbounded"
				ref="address">
			</xs:element>
			<xs:element minOccurs="0" maxOccurs="unbounded"
				ref="connection">
			</xs:element>
			<xs:element minOccurs="0" maxOccurs="unbounded"
				ref="association">
			</xs:element>
			<xs:element minOccurs="0" maxOccurs="1" ref="medical"></xs:element>
		</xs:choice>
		<xs:attribute name="birthdate" type="xs:NMTOKEN"></xs:attribute>
		<xs:attribute name="firstname" type="xs:NMTOKEN"></xs:attribute>
		<xs:attribute use="required" name="id" type="xs:NMTOKEN"></xs:attribute>
		<xs:attribute name="lastname" type="xs:NMTOKEN"></xs:attribute>
		<xs:attribute name="middlename" type="xs:NMTOKEN"></xs:attribute>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="salutation" type="xs:NMTOKEN"></xs:attribute>
		<xs:attribute name="sex" type="xs:NMTOKEN"></xs:attribute>
		<xs:attribute name="title" type="xs:NMTOKEN"></xs:attribute>
		<xs:attribute use="required" name="type" type="xs:NMTOKEN"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="xChangeDocument">
		<xs:sequence>
			<xs:element minOccurs="0" ref="summary"></xs:element>
		</xs:sequence>
		<xs:attribute name="content" type="xs:NMTOKEN"></xs:attribute>
		<xs:attribute name="creatorID" type="xs:NMTOKEN"></xs:attribute>
		<xs:attribute name="creatorName" type="xs:NMTOKEN"></xs:attribute>
		<xs:attribute use="required" name="date" type="xs:NMTOKEN"></xs:attribute>
		<xs:attribute name="dest" type="xs:integer"></xs:attribute>
		<xs:attribute name="hint" type="xs:string"></xs:attribute>
		<xs:attribute use="required" name="id" type="xs:NMTOKEN"></xs:attribute>
		<xs:attribute name="origin" type="xs:integer"></xs:attribute>
		<xs:attribute name="record" type="xs:NMTOKEN"></xs:attribute>
		<xs:attribute name="responsible" type="xs:integer"></xs:attribute>
		<xs:attribute name="title" type="xs:string"></xs:attribute>
		<xs:attribute name="type" type="xs:string"></xs:attribute>
		<xs:attribute name="version" type="xs:NMTOKEN"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="xChangeEpisode">
		<xs:sequence>
			<xs:element minOccurs="0" ref="diagnosis"></xs:element>
			<xs:element minOccurs="0" ref="text"></xs:element>
			<xs:element name="insurance" type="insuranceType"></xs:element>
		</xs:sequence>
		<xs:attribute name="begin" type="xs:date"></xs:attribute>
		<xs:attribute use="required" name="id" type="xs:string"></xs:attribute>
		<xs:attribute name="active" type="xs:boolean"></xs:attribute>
		<xs:attribute name="title" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="insuranceType">


		<xs:sequence>
			<xs:element name="contract" type="tariffType"
				maxOccurs="unbounded" minOccurs="1">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="contactref" type="xs:string"></xs:attribute>
		<xs:attribute name="reason">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="disease"></xs:enumeration>
					<xs:enumeration value="accident"></xs:enumeration>
					<xs:enumeration value="maternity"></xs:enumeration>
					<xs:enumeration value="prevention"></xs:enumeration>
					<xs:enumeration value="birthdefect"></xs:enumeration>
					<xs:enumeration value="other"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>


		<xs:attribute name="publicDiagnosis" type="xs:string"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="tariffType">
		<xs:attribute name="country">
			<xs:annotation>
				<xs:documentation>
					ISO Countrycode for the country, that tariff applies
				</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="1"></xs:minLength>
					<xs:maxLength value="3"></xs:maxLength>
					<xs:whiteSpace value="collapse"></xs:whiteSpace>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="name" type="xs:string"></xs:attribute>
		<xs:attribute name="caseID" type="xs:string"></xs:attribute>
	</xs:complexType>
	
    <xs:attribute name="contactref" type="xs:string"></xs:attribute>
</xs:schema>

=== hilotec/elexis-base/elexis/src/ch/elexis/exchange/EMRSample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- example of a Sgam.eXchange - file
/*******************************************************************************
* Copyright (c) 2006, G. Weirich and Sgam.informatics
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the Eclipse Public License v1.0
* which accompanies this distribution, and is available at
* http://www.eclipse.org/legal/epl-v10.html
*
* Contributors:
*    G. Weirich - initial implementation
*    
*  $Id: EMRSample.xml 1292 2006-11-19 09:55:29Z rgw_ch $
*******************************************************************************/
-->
<XCHANGE xmlns="SgamXChange" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="SgamXChange xchange.xsd">
	<!--xsi:schemaLocation="SgamXChange SgamXChange.xsd" -->
	<!-- Deklaration der verwendeten eXChange Version und des Erstellers der Datei, sowie 
	des Datums, an dem diese Datei erstellt wurde und eine eindeutige ID-->
	<document version="0.1.0" creatorName="elexis" creatorID="www.elexis.ch"
		date="2006-10-18" id="1bc12434521" responsible="007"/>
	
	<contact type="person" lastname="Testperson" middlename="X."
		firstname="Armeswesen" birthdate="1950-10-12" sex="male"
		id="165.23.456.212">
		
		<address type="default">
			<street>DieseGasse 27</street>
			<zip>9999</zip>
			<city>Elexikon</city>
			<country>CH</country>
			<phone>555-123456</phone>
		</address>
		
		<connection type="mobile" identification="555-99123"/>
		<connection type="e-mail" identification="testperson@armeswesen.ch"/>
		<connection type="skype" identification="armtestwesen"/>
		<connection type="web"
			identification="http://www.testperson-armeswesen.ch"/>
		
		<address type="work">
			<street>Hauptstrasse 27</street>
			<zip>8888</zip>
			<city>Anderswo</city>
		</address>
		<contactref type="spouse" id="165.23.456.23"/>
		
		<medical>
			<!-- anamnestic episodes -->
			<anamnesis>
				<!-- a single episode -->
				<episode date="2005-10-15" title="Tibiafraktur"
					inactive="2005-12-10" id="234">
					<diagnosis codesystem="ICD-10" code="Z00"/>
					<text>Beim Skifahren rechtes Bein gebrochen</text>
				</episode>
				<episode date="2003-12-01" title="Hypertonie" id="567">
					<diagnosis codesystem="TICode" code="A00"/>
					<text>Essentielle Hypertonie</text>
				</episode>
			</anamnesis>
			<!-- collection of all medical records -->
			<records>
				<record date="2006-08-24" author="gerry" responsible="0de122333"
					id="0ab12UUID">
					<text>Dies ist ein unstrukturierter KG-Eintrag.</text>
					<episode id="234"/>
					
				</record>
				<record date="2006-08-30" author="gerry" responsibleEAN="012333"
					id="0ab13UUID">
					<text>
						<section name="Subjektiv">Dies ist ein strukturierter
							KG-Eintrag</section>
						<section name="Objektiv"></section>
						<section name="Beurteilung">Heute alles in Butter</section>
						<section name="Procedere"></section>
					</text>
					<episode id="234"/>
					<episode id="567"/>
				</record>
				
			</records>
			
			<!-- collection of all analyses. Every analyse comes from a specified institution, and the Result can be normal,
			abnormal or indeterminate 
			-->
			<analyses>
				<!-- An Analyse classified according LOINC -->
				<analyse classification="LOINC" lab="3425" param="2828-2"
					date="2006-07-23" abnormal="false">
					<result>3.8</result>
				</analyse>
				
				
				<!-- An analyse whose result can be expressed as number within or outside a norm range -->
				<analyse classification="lab" date="2006-08-24" lab="122345"
					param="Hb" type="number" normRange="10.0-15.0" unit="mmol/l"
					abnormal="true">
					<result>9.2</result>
				</analyse>
				
				
				<!-- An analyse whose result is an unstructured text. The text itself is referenced externally -->
				<analyse date="2006-08-24" lab="122345" param="Sputumzytologie"
					type="docref" id="doc001" abnormal="false" classification="lab"/>
				
				<!-- An analyse whose result is either positive or negative -->
				<analyse date="2006-08-24" lab="122345" param="HIV suchtest"
					type="absolute" abnormal="false" classification="lab">
					<result>negativ</result>
				</analyse>
				
				<!-- Some analyses whose results can be viewed as images -->
				<analyse date="2006-09-19" classification="lab" lab="122345"
					param="Eiweiss-Elektrophorese" type="docref" id="doc002"
					abnormal="true">
					<result>Hypalbuminämie</result>
				</analyse>
				
				<analyse classification="lab" date="2006-08-24" lab="122345"
					type="docref" param="MRI Gehirn" id="doc003" abnormal="false">
					<result>unauffällig</result>
				</analyse>
				
				<analyse classification="lab" date="2006-08-24" lab="012333"
					abnormal="false" param="EKG" type="docref" id="doc004">
					<result>nc SR, LLT, unauff. de- undRepol. </result>
				</analyse>
				
				<!-- An analyse with a nested image which is enclosed base64 encoded. An application that is not able to display images is 
				adviced to ignore the image silently and show only the text -->
				<analyse classification="lab" date="2006-08-24" lab="012333"
					param="Rx Thorax pa und seitlich" abnormal="true" id="344554">
					<image id="rqwerq§4qwreqr" content="inline" hint="ignore">
						1245123534534523656463456#xD;
						4564576376765767675675675#xD;
						5675675675676656756745675#xD;
						qwerqwrterwztzruzejuezuzu#xD; </image>
					<result>Infiltrat li Oberlappen</result>
				</analyse>
				
			</analyses>
			
			<!-- collection of all documents concerning this patient exchanged between
			the creator of the document and other institutions or persons. A document can be of
			any mime-type, which must be declared as type-attribute -->
			
			<documents>
				<!-- A document which is a picture -->
				<document date="2006-02-20" type="image/jpeg"
					title="Nävus am rechten Vorderarm" id="12234432" content="ext"
					origin="007" record="0ab12UUID">
					<summary>Auffälliger Nävus zur Verlaufskontrolle</summary>
				</document>
				
				<!-- an outgoing document -->
				<document date="2006-08-24" type="application/msword" dest="23234"
					title="Anmeldung ergometrie" id="0982423UUID" content="ext"
					record="0ab12UUID"
					hint="replace: Anmeldung Kardiologie KSSH"/>
				
				<!-- Some analyses (referenced from analyses - Block)  -->
				<document date="2006-08-24" id="doc001" type="text/plain"
					origin="122345" title="Sputumzytologie" content="ext"
					hint="ignore"/>
				
				<document date="2006-06-19" type="image/png" content="ext"
					id="doc002" title="Eiweiss-Elektrophorese"/>
				
				<document date="2006-08-24" id="doc003" type="image/DICOM"
					content="ext" title="MRI Gehirn"
					hint="warn: Bild kann nicht angezeigt werden"/>
				
				<document date="2006-08-24" type="image/jpeg" id="doc004"
					content="ext" title="Ruhe-EKG"
					hint="warn: Bild kann nicht angezeigt werden"/>
				
			</documents>
			<medications>
				<medication id="1124324534" substance="metoprololi"
					start="2006-01-01" last="2006-05-06" dosage="1-0-0">Beloc ZOK
					100mg</medication>
				<medication id="7680519460224"
					substance="Quinalaprilum,Hydrochlorothiazidum"
					start="2006-02-05" last="2006-06-08" dosage="1-0-0">Accuretic
					20/12.5</medication>
			</medications>
			<allergies>
				<allergy substance="acidum acetylsalicylicum" first="2005-01-04"
					confirmed="no">ASS</allergy>
				<allergy substance="wasp" first="2004-08-12" confirmed="yes">
					Wespenstich</allergy>
			</allergies>
		</medical>
	</contact>
	
	<contact type="organization" name="SWICA Gesundheitsorganisation"
		id="7601003002041">
		<address type="work">
			<street>Bahnhofstrasse 8</street>
			<zip>8200</zip>
			<city>Schaffhausen</city>
		</address>
	</contact>
	
	<contact type="person" lastname="Busch" middlename="Dabbeljuh"
		firstname="Dschordsch" birthdate="1941-06-06" id="007" title="presi"
		salutation="Mistärr">
	</contact>
	
	<contact type="person" lastname="Testerella" firstname="Kunigunde"
		birthdate="1955-03-08" id="165.23.456.23">
		<address type="home">
			<street>Marktstrasse 7</street>
			<zip>D-992344</zip>
			<city>Deutschhausen</city>
		</address>
	</contact>
	
	<contact type="organization" name="Labor Prof. Dr. V. Ampir" id="122345">
		<address type="default">
			<street>Hintergasse 27</street>
			<zip>9998</zip>
			<city>Ost-Elexikon</city>
			<phone>555-123456</phone>
		</address>
		<connection type="fax" identification="555-999888"/>
		<connection type="fernabfrage"
			identification="https://www.vampir.ch/befunde"/>
	</contact>
	
</XCHANGE>
